fix: add super init call to ColorFormatter
Without this the _style attribute is missing and the exception method fails:

    --- Logging error ---
    Traceback (most recent call last):
      File "x.py", line 11, in <module>
        1/0
    ZeroDivisionError: division by zero

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "env/lib/python3.8/site-packages/click_logging/core.py", line 49, in emit
        msg = self.format(record)
      File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
        return fmt.format(record)
      File "env/lib/python3.8/site-packages/click_logging/core.py", line 39, in format
        return logging.Formatter.format(self, record)
      File "/usr/lib/python3.8/logging/__init__.py", line 669, in format
        if self.usesTime():
      File "/usr/lib/python3.8/logging/__init__.py", line 637, in usesTime
        return self._style.usesTime()
    AttributeError: 'ColorFormatter' object has no attribute '_style'
    Call stack:
      File "x.py", line 13, in <module>
        logger.exception("Exception.")
      File "/usr/lib/python3.8/logging/__init__.py", line 1481, in exception
        self.error(msg, *args, exc_info=exc_info, **kwargs)
      File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
        self._log(ERROR, msg, args, **kwargs)
      File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
        self.handle(record)
      File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
        self.callHandlers(record)
      File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
        hdlr.handle(record)
      File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
        self.emit(record)
      File "env/lib/python3.8/site-packages/click_logging/core.py", line 56, in emit
        self.handleError(record)
    Message: 'Exception.'
    Arguments: ()