fix: fix echo_kwargs example in readme
This value needs to be a dictionary, not a bool:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "src/logging.py", line 30, in <module>
        logger = get_logger('app')
      File "src/logging.py", line 24, in get_logger
        click_logging.basic_config(logger, echo_kwargs=True)
      File "env/lib/python3.8/site-packages/click_logging/core.py", line 89, in basic_config
        echo_kwargs = _normalize_echo_kwargs(echo_kwargs)
      File "env/lib/python3.8/site-packages/click_logging/core.py", line 80, in _normalize_echo_kwargs
        normamized_echo_kwargs.update(echo_kwargs)
    TypeError: 'bool' object is not iterable